apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-creds
  namespace: mlflow-model
type: Opaque
stringData:
  access-key: minio
  secret-key: minioadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mlflow
  namespace: mlflow-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-mlflow
  template:
    metadata:
      labels:
        app: vllm-mlflow
    spec:
      containers:
        - name: vllm-mlflow
          image: nirmesh44/vllm-mlflow:latest
          ports:
            - containerPort: 9000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-server.mlflow-model.svc.cluster.local:5000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-creds
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-minio-creds
                  key: secret-key
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://mlflow-minio.mlflow-model.svc.cluster.local:9000"
            - name: MODEL_NAMES
              value: "invoice-model"  # comma separated list of models to auto-load
          volumeMounts:
            - name: model-cache
              mountPath: /models
      volumes:
        - name: model-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-mlflow
  namespace: mlflow-model
spec:
  selector:
    app: vllm-mlflow
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 31310
